from sqlalchemy import Column, String, Text, DateTime
from sqlalchemy.sql import func
from app.database import Base


class ConversationHistory(Base):
    """
    Stores every message in every chat session.
    session_id  — unique ID generated by the React widget (uuid)
    role        — either "user" or "assistant"
    content     — the message text
    firm_id     — which client's bot this belongs to (e.g. "acme-law")
    created_at  — auto-set timestamp
    """
    __tablename__ = "conversation_history"

    id = Column(String, primary_key=True, index=True)
    session_id = Column(String, index=True, nullable=False)
    firm_id = Column(String, index=True, nullable=False, default="demo")
    role = Column(String, nullable=False)       # "user" or "assistant"
    content = Column(Text, nullable=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
